# Generated by Django 4.2.27 on 2026-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_documento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='confianza_ia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tags_ia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='texto_detectado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando IA'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
