# Generated by Django 4.2.27 on 2026-01-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_documento_confianza_ia_documento_tags_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
