# Generated by Django 4.2.27 on 2026-01-07 21:03

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_documento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
