"""
Django settings for retail_dam project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'channels',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'retail_dam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'retail_dam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
	'PASSWORD': os.environ.get('DB_PASS'),
	'HOST': os.environ.get('DB_HOST', 'db'),
	'PORT': '5432',
	
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True
USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#-- configuracion aws --

# usamos Boto3 para que las credenciales del rol iam de la ec2 automaticamente

AWS_STORAGE_BUCKET_NAME = 'perfumeria-lab-2025'
AWS_S3_REGION_NAME = 'us-east-1'


# 1. Esto evita que Django intente cambiar los permisos ACL (S3 moderno lo bloquea)
AWS_DEFAULT_ACL = None 



#Configuración híbrida: Usa env vars si existen, sino confía en el Rol IAM (EC2)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', None)
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', None)
AWS_SESSION_TOKEN = os.getenv('AWS_SESSION_TOKEN', None)
    
# configuracion de archivos privados vs publicos
AWS_QUERYSTRING_AUTH = True
AWS_S3_SIGNATURE_VERSION = 's3v4'


#  Fuerza el uso de URLs tipo "bucket.s3.amazonaws.com" (más compatible con firma v4)
AWS_S3_ADDRESSING_STYLE = "virtual"


# esto le dice a django: usa s3 para todo lo que suban los usuarios
DEFAULT_FILE_STORAGE ='storages.backends.s3boto3.S3Boto3Storage'

#opcional : para que no soescriba archivos con el mismo nombre
AWS_S3_FILE_OVERWRITE = False



#--- configuracion de archivos estaticos (css, js, imagenes) ----
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',

]

#-- redirecciones de Login ---
# cuando se logueen van a la vista de subir archivo
LOGIN_REDIRECT_URL = 'subir_archivo'
# cuando salen , vuelven al login 
LOGOUT_REDIRECT_URL ='login'

#  -- CONFIGURACION CELERY ---
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Santiago'


# --- SEGURIDAD CSRF PARA AWS ---
# Esto permite que el Logout funcione desde tu IP pública
CSRF_TRUSTED_ORIGINS = [
    "http://54.172.95.236",       # Tu IP sin puerto
    "http://54.172.95.236:8000",  # Tu IP con puerto
    "http://18.212.98.166",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Configuración ASGI para WebSockets
ASGI_APPLICATION = 'retail_dam.asgi.application'  # Asegúrate que 'retail_dam' es el nombre de tu carpeta de proyecto

# Configuración del Canal (Usando tu Redis existente)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)], # Tu Redis local
        },
    },
}
